# Generated by Django 5.1.7 on 2025-03-25 13:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название кафедры')),
            ],
        ),
        migrations.CreateModel(
            name='EducationLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Уровень образования')),
                ('code', models.CharField(max_length=20, verbose_name='Код уровня')),
            ],
        ),
        migrations.CreateModel(
            name='PartnerCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название компании')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='partners/')),
            ],
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='Код направления')),
                ('name', models.CharField(max_length=255, verbose_name='Название направления')),
                ('program_name', models.CharField(max_length=255, verbose_name='Название программы')),
                ('form', models.CharField(default='Очная', max_length=50, verbose_name='Форма обучения')),
                ('description', models.TextField(verbose_name='Описание программы')),
                ('career_opportunities', models.TextField(verbose_name='Кем можно работать')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='directions.department')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='programs', to='directions.educationlevel')),
            ],
        ),
        migrations.CreateModel(
            name='ProgramFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок особенности')),
                ('description', models.TextField(verbose_name='Описание')),
                ('program', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='directions.program')),
            ],
        ),
    ]
