# Generated by Django 5.1.7 on 2025-05-01 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directions', '0002_remove_program_created'),
    ]

    operations = [
        # migrations.RenameField(
        #     model_name='program',
        #     old_name='created',
        #     new_name='created_at',
        # ),
    ]
