# Generated by Django 5.1.7 on 2025-05-01 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directions', '0003_rename_created_program_created_at'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='program',
        #     name='created',
        # ),
        # migrations.RemoveField(
        #     model_name='program',
        #     name='updated',
        # ),
    ]
