# Generated by Django 5.1.7 on 2025-05-28 01:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directions', '0004_remove_program_created_remove_program_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name'], 'verbose_name': 'Кафедра', 'verbose_name_plural': 'Кафедры'},
        ),
        migrations.AlterModelOptions(
            name='educationlevel',
            options={'ordering': ['name'], 'verbose_name': 'Уровень образования', 'verbose_name_plural': 'Уровни образования'},
        ),
        migrations.AlterModelOptions(
            name='partnercompany',
            options={'ordering': ['name'], 'verbose_name': 'Партнер', 'verbose_name_plural': 'Партнеры'},
        ),
        migrations.AlterModelOptions(
            name='program',
            options={'ordering': ['code', 'program_name'], 'verbose_name': 'Программа', 'verbose_name_plural': 'Программы'},
        ),
        migrations.AlterModelOptions(
            name='programfeature',
            options={'ordering': ['order', 'title'], 'verbose_name': 'Особенность', 'verbose_name_plural': 'Особенности'},
        ),
        migrations.AlterUniqueTogether(
            name='program',
            unique_together={('code', 'program_name', 'form')},
        ),
        migrations.AddField(
            model_name='partnercompany',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='is_active',
            field=models.BooleanField(default=True, null=True, verbose_name='Активна'),
        ),
        migrations.AddField(
            model_name='program',
            name='updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='programfeature',
            name='order',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(3, 'Название должно содержать минимум 3 символа'), django.core.validators.MaxLengthValidator(255, 'Название слишком длинное')], verbose_name='Название кафедры'),
        ),
        migrations.AlterField(
            model_name='educationlevel',
            name='code',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Код уровня'),
        ),
        migrations.AlterField(
            model_name='educationlevel',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Уровень образования'),
        ),
        migrations.AlterField(
            model_name='partnercompany',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='partners/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='partnercompany',
            name='name',
            field=models.CharField(max_length=255, unique=True, validators=[django.core.validators.MinLengthValidator(3)], verbose_name='Название компании'),
        ),
        migrations.AlterField(
            model_name='program',
            name='career_opportunities',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(20)], verbose_name='Кем можно работать'),
        ),
        migrations.AlterField(
            model_name='program',
            name='code',
            field=models.CharField(max_length=20, validators=[django.core.validators.MinLengthValidator(2)], verbose_name='Код направления'),
        ),
        migrations.AlterField(
            model_name='program',
            name='description',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(50)], verbose_name='Описание программы'),
        ),
        migrations.AlterField(
            model_name='program',
            name='form',
            field=models.CharField(choices=[('FT', 'Очная'), ('PT', 'Очно-заочная'), ('DL', 'Заочная')], default='FT', max_length=50, verbose_name='Форма обучения'),
        ),
        migrations.AlterField(
            model_name='program',
            name='name',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Название направления'),
        ),
        migrations.AlterField(
            model_name='program',
            name='program_name',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Название программы'),
        ),
        migrations.AlterField(
            model_name='programfeature',
            name='description',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='programfeature',
            name='title',
            field=models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(5)], verbose_name='Заголовок особенности'),
        ),
        migrations.RemoveField(
            model_name='program',
            name='created',
        ),
        migrations.RemoveField(
            model_name='program',
            name='updated',
        ),
    ]
