# Generated by Django 5.1.7 on 2025-05-30 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directions', '0005_alter_department_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnercompany',
            name='website',
        ),
    ]
