# Generated by Django 5.1.7 on 2025-06-12 09:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proftesting', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='testsession',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='testresult',
            name='session',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='result', to='proftesting.testsession'),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proftesting.answeroption'),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proftesting.question'),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='proftesting.testsession'),
        ),
        migrations.AlterUniqueTogether(
            name='answerprogramweight',
            unique_together={('answer_option', 'program')},
        ),
        migrations.AlterUniqueTogether(
            name='useranswer',
            unique_together={('session', 'question')},
        ),
    ]
