# Generated by Django 5.1.7 on 2025-05-01 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proftesting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answeroption',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='testresult',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
