# Generated by Django 5.1.7 on 2025-05-01 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proftesting', '0002_answeroption_updated_testresult_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answeroption',
            name='updated',
        ),
        migrations.RemoveField(
            model_name='testresult',
            name='updated',
        ),
    ]
