# Generated by Django 5.1.7 on 2025-06-12 07:19

import server.settings.environments.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0002_alter_achievement_image_alter_banner_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название документа')),
                ('file', models.FileField(storage=server.settings.environments.storage_backends.YandexMediaStorage(), upload_to='organization_documents/', verbose_name='Файл документа')),
            ],
            options={
                'verbose_name': 'Документ организации',
                'verbose_name_plural': 'Документы организации',
            },
        ),
        migrations.CreateModel(
            name='VideoContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название видео')),
                ('video_url', models.URLField(verbose_name='Ссылка на видео (YouTube/Vimeo и т.д.)')),
                ('description', models.TextField(blank=True, verbose_name='Описание видео')),
            ],
            options={
                'verbose_name': 'Видео контент',
                'verbose_name_plural': 'Видео контент',
            },
        ),
    ]
