# Generated by Django 5.1.7 on 2025-06-14 21:05

import server.settings.environments.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Content', '0003_organizationdocument_videocontent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='videocontent',
            name='video_url',
        ),
        migrations.AddField(
            model_name='videocontent',
            name='file',
            field=models.FileField(default=123, storage=server.settings.environments.storage_backends.YandexMediaStorage(), upload_to='organization_documents/', verbose_name='Видео'),
            preserve_default=False,
        ),
    ]
