# Generated by Django 5.1.7 on 2025-05-29 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='title',
        ),
    ]
