# Generated by Django 5.1.7 on 2025-05-29 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0002_remove_application_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='status',
            field=models.CharField(choices=[('pending', 'На рассмотрении'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], default='pending', max_length=50, verbose_name='Статус'),
        ),
    ]
