# Generated by Django 5.1.7 on 2025-06-14 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0004_alter_application_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название типа')),
                ('code', models.SlugField(unique=True, verbose_name='Код типа')),
            ],
            options={
                'verbose_name': 'Тип заявления',
                'verbose_name_plural': 'Типы заявлений',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='application',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='Application.applicationtype', verbose_name='Тип заявления'),
        ),
    ]
