# Generated by Django 5.1.7 on 2025-06-07 20:28

import django.db.models.deletion
import server.settings.environments.storage_backends
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, storage=server.settings.environments.storage_backends.YandexMediaStorage(), upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='email address'),
        ),
        migrations.CreateModel(
            name='UserPhone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_phone', models.BinaryField()),
                ('phone_hash', models.CharField(max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='phone_data', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Телефон пользователя',
                'verbose_name_plural': 'Телефоны пользователей',
            },
        ),
    ]
