# Generated by Django 5.1.7 on 2025-06-07 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_avatar_alter_user_email_userphone'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='user',
            name='users_user_phone_9474e8_idx',
        ),
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
    ]
