# Generated by Django 5.1.7 on 2025-05-22 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_appeal_appealresponse_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppealAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='appeals/attachments/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('appeal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='users.appeal')),
            ],
        ),
    ]
