# Generated by Django 5.1.7 on 2025-06-12 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_users_user_phone_9474e8_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userphone',
            name='user',
        ),
        migrations.AlterField(
            model_name='user',
            name='middle_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='middle name'),
        ),
        migrations.AlterField(
            model_name='userphone',
            name='phone_hash',
            field=models.CharField(max_length=64),
        ),
        migrations.DeleteModel(
            name='PhoneVerification',
        ),
    ]
