# Generated by Django 5.1.7 on 2025-05-25 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_appealattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='vk_id',
            field=models.BigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
