# Generated by Django 5.1.7 on 2025-03-18 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_remove_comment_is_active_remove_news_views_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='slug',
        ),
    ]
