# Generated by Django 5.1.7 on 2025-05-28 01:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_remove_newsimage_news_alter_news_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsimage',
            name='news',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='news.news'),
            preserve_default=False,
        ),
    ]
