# Generated by Django 5.1.7 on 2025-03-18 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_remove_tag_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
    ]
