# Generated by Django 5.1.7 on 2025-05-28 02:46

import server.settings.environments.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_newsimage_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='image',
            field=models.ImageField(blank=True, null=True, storage=server.settings.environments.storage_backends.YandexMediaStorage(), upload_to='news_images/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='newsimage',
            name='image',
            field=models.ImageField(storage=server.settings.environments.storage_backends.YandexMediaStorage(), upload_to='news_images/'),
        ),
    ]
