# Generated by Django 5.1.7 on 2025-03-18 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_remove_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='slug',
        ),
    ]
