# Generated by Django 5.1.7 on 2025-03-18 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_alter_news_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='slug',
            field=models.SlugField(max_length=200, null=True, unique=True, verbose_name='URL новости'),
        ),
    ]
