# Generated by Django 5.1.7 on 2025-05-18 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perscalendar', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['start_time'], 'verbose_name': 'Событие', 'verbose_name_plural': 'События'},
        ),
        migrations.AddField(
            model_name='event',
            name='recurrence_end',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Окончание повторений'),
        ),
        migrations.AddField(
            model_name='userevent',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время выполнения'),
        ),
        migrations.AlterField(
            model_name='event',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_events', to=settings.AUTH_USER_MODEL, verbose_name='Создатель'),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_time',
            field=models.DateTimeField(verbose_name='Время окончания'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('personal', 'Личное'), ('group', 'Групповое'), ('global', 'Общее'), ('deadline', 'Дедлайн')], default='personal', max_length=10, verbose_name='Тип события'),
        ),
        migrations.AlterField(
            model_name='event',
            name='group_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ID группы'),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_recurring',
            field=models.BooleanField(default=False, verbose_name='Повторяющееся'),
        ),
        migrations.AlterField(
            model_name='event',
            name='recurrence_rule',
            field=models.JSONField(blank=True, null=True, verbose_name='Правило повторения'),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_time',
            field=models.DateTimeField(verbose_name='Время начала'),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название'),
        ),
    ]
