# Generated by Django 5.1.7 on 2025-05-28 02:47

import server.settings.environments.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virtmuseum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audienceimage',
            name='image',
            field=models.ImageField(storage=server.settings.environments.storage_backends.YandexMediaStorage(), upload_to='audience_images/', verbose_name='Изображение'),
        ),
    ]
